### ISSUE TITLE
Error during build as atomicAdd

### ISSUE THREAD

**Issue by Zhaojp-Frank** [GPUPeople/spECK#1]
thanks for sharing the repo.
I tried to build it on Ubuntu, but hit error about atomicAdd, any help here? thanks a lot
env:
cuda10.1
gcc 7.4.0
cmake 3.15
error msg:
/github/spECK/include/GPU/spECK_HashSpGEMM.cuh(1248): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during:
            instantiation of "void iterateMatrixDenseNumeric<INDEX_TYPE,VALUE_TYPE,MAX_ELEMENTS_BLOCK,SUPPORT_GLOBAL,THREADS,SHIFT,useRowOffsets>(INDEX_TYPE, INDEX_TYPE, uint32_t, INDEX_TYPE *, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, const INDEX_TYPE *, const INDEX_TYPE *, const INDEX_TYPE *, const VALUE_TYPE *, const VALUE_TYPE *, INDEX_TYPE *, VALUE_TYPE *, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE *, INDEX_TYPE *, INDEX_TYPE *, VALUE_TYPE *, void *) [with INDEX_TYPE=IndexType, VALUE_TYPE=double, MAX_ELEMENTS_BLOCK=5325U, SUPPORT_GLOBAL=false, THREADS=1024U, SHIFT=10U, useRowOffsets=true]"
(1392): here
            instantiation of "void denseSpGEMMNumericImplementation<INDEX_TYPE,VALUE_TYPE,GlobalRowOffsetsMap,SHARED_MEM_SIZE,SUPPORT_GLOBAL,THREADS>(INDEX_TYPE, INDEX_TYPE, const INDEX_TYPE *, const INDEX_TYPE *, const INDEX_TYPE *, const VALUE_TYPE *, const VALUE_TYPE *, GlobalRowOffsetsMap *, INDEX_TYPE, INDEX_TYPE *, VALUE_TYPE *, const INDEX_TYPE *, uint32_t *, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, __nv_bool, uint32_t) [with INDEX_TYPE=IndexType, VALUE_TYPE=double, GlobalRowOffsetsMap=HashMapNoValue<uint32_t, 1UL>, SHARED_MEM_SIZE=48384U, SUPPORT_GLOBAL=false, THREADS=1024U]"
(1764): here
            instantiation of "void spGEMMNumericLauncher<INDEX_TYPE,VALUE_TYPE,GlobalHashMap,GlobalRowOffsetMap,SHARED_MEM_SIZE,SUPPORT_GLOBAL,THREADS>(INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, INDEX_TYPE, const INDEX_TYPE *, const INDEX_TYPE *, const INDEX_TYPE *, const INDEX_TYPE *, const VALUE_TYPE *, const VALUE_TYPE *, GlobalHashMap *, INDEX_TYPE, GlobalRowOffsetMap *, INDEX_TYPE, INDEX_TYPE *, VALUE_TYPE *, const INDEX_TYPE *, INDEX_TYPE *, const INDEX_TYPE *, Config::SortModes, uint32_t, const INDEX_TYPE *, uint32_t *, uint32_t, __nv_bool, uint32_t) [with INDEX_TYPE=IndexType, VALUE_TYPE=double, GlobalHashMap=HashMap<uint32_t, double>, GlobalRowOffsetMap=HashMapNoValue<uint32_t, 1UL>, SHARED_MEM_SIZE=48384U, SUPPORT_GLOBAL=false, THREADS=1024U]"
(2021): here
            instantiation of "void spECKKernels::h_SpGEMMNumericLauncher<INDEX_TYPE,VALUE_TYPE,GlobalHashMap,GlobalRowOffsetMap,SHARED_HASH_SIZE,SUPPORT_GLOBAL,THREADS>(dCSRNoDealloc<VALUE_TYPE>, dCSRNoDealloc<VALUE_TYPE>, dCSRNoDealloc<VALUE_TYPE>, GlobalHashMap *, INDEX_TYPE, GlobalRowOffsetMap *, INDEX_TYPE, INDEX_TYPE *, INDEX_TYPE *, Config::SortModes, uint32_t, const INDEX_TYPE *, INDEX_TYPE *, uint32_t, __nv_bool, uint32_t) [with INDEX_TYPE=IndexType, VALUE_TYPE=double, GlobalHashMap=HashMap<uint32_t, double>, GlobalRowOffsetMap=HashMapNoValue<uint32_t, 1UL>, SHARED_HASH_SIZE=48384U, SUPPORT_GLOBAL=false, THREADS=1024U]"
/github/spECK/source/GPU/Multiply.cu(864): here
            instantiation of "void spECK::MultiplyspECKImplementation<DataType,BLOCKS_PER_SM,THREADS_PER_BLOCK,MAX_DYNAMIC_SHARED,MAX_STATIC_SHARED>(const dCSR<DataType> &, const dCSR<DataType> &, dCSR<DataType> &, spECK::spECKConfig &, Timings &) [with DataType=double, BLOCKS_PER_SM=4, THREADS_PER_BLOCK=1024, MAX_DYNAMIC_SHARED=49152, MAX_STATIC_SHARED=49152]"
/github/spECK/source/GPU/Multiply.cu(1133): here
            instantiation of "void spECK::MultiplyspECK<DataType,BLOCKS_PER_SM,THREADS_PER_BLOCK,MAX_DYNAMIC_SHARED,MAX_STATIC_SHARED>(const dCSR<DataType> &, const dCSR<DataType> &, dCSR<DataType> &, spECK::spECKConfig &, Timings &) [with DataType=double, BLOCKS_PER_SM=4, THREADS_PER_BLOCK=1024, MAX_DYNAMIC_SHARED=49152, MAX_STATIC_SHARED=49152]"
/github/spECK/source/GPU/Multiply.cu(1137): here

Error limit reached.
100 errors detected in the compilation of "Multiply.cpp1.ii".
Compilation terminated.
CMakeFiles/spECKLib.dir/build.make:153: recipe for target 'CMakeFiles/spECKLib.dir/source/GPU/Multiply.cu.o' failed
make[2]: *** [CMakeFiles/spECKLib.dir/source/GPU/Multiply.cu.o] Error 1
CMakeFiles/Makefile2:76: recipe for target 'CMakeFiles/spECKLib.dir/all' failed
make[1]: *** [CMakeFiles/spECKLib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dabeschte** [comment]
Hey! Sorry for taking so long. I did not get a notification from Github.
Yes, I think I know the solution and I will update the readme accordingly.

Did you set one of the options "CUDA_BUILD_CCxx" in the CMakeLists.txt file to true?
This will set the compute capability depending on your hardware version.
You can find out which CC you should use on [Wikipedia](https://en.wikipedia.org/wiki/CUDA).

edit: Oh I just noticed that I already mentioned that step in the readme under step 6.
But you can also just override the value in the CMakeLists.txt.

**Comment by oryabkov** [comment]
Hello! 
I have stuck on this problem either. I have CUDA 10.2 version and GeForce GTX TITAN X card, which is 5.2 CC. I've set COMPUTE_CAPABILITY="CC52" in linuxsetup.sh but still got a lot of errors, last of them is:
../spECK_HashSpGEMM.cuh(1227): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
Ubuntu 20.04, gcc 8.4.0

**Comment by dabeschte** [comment]
@oryabkov CC 5.2 unfortunately does not support atomicAdd for 64 bit "double". The easiest solution is to disable compilation for double by commenting out [this line](https://github.com/GPUPeople/spECK/blob/815659952c6e8174e81819aff6ad39377cc57afc/source/GPU/Multiply.cu#L1131) and only use 32-bit floating point numbers "float"  if that is an option for your use case.

In case you want to use double precision SpGEMM, you need to manually define atomicAdd for this generation as discussed in [this issue](https://stackoverflow.com/questions/37566987/cuda-atomicadd-for-doubles-definition-error). But keep in mind that that will have a large impact on the performance.
